### Hilfe erhalten
Hierzu bedarf es lediglich eines vorangestellten Fragezeichens

In [1]:
?plot

In [2]:
x = c(1:5)
x

[1] 1 2 3 4 5

In [3]:
y = "Hier bin ich!"
y

[1] "Hier bin ich!"

In [4]:
c = c(1+3i)
c

[1] 1+3i

## Spezielle Werte (NA, +/- Inf, NaN)

In [6]:
z = c(1,2,3,NA,5,NA)
z

[1]  1  2  3 NA  5 NA

In [7]:
complete.cases(z)
is.na(z)

[1]  TRUE  TRUE  TRUE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE  TRUE FALSE  TRUE

In [8]:
1/0

[1] Inf

In [9]:
0/0

[1] NaN

In [10]:
-1/0

[1] -Inf

In [13]:
m = c(2/3,3/3,0/0,-1/0,1/0)
m

[1] 0.6666667 1.0000000       NaN      -Inf       Inf

In [14]:
is.finite(m)

[1]  TRUE  TRUE FALSE FALSE FALSE

In [15]:
is.infinite(m)

[1] FALSE FALSE FALSE  TRUE  TRUE

In [16]:
is.nan(m)

[1] FALSE FALSE  TRUE FALSE FALSE

### Entfernen fehlender Daten

In [18]:
clean <- complete.cases(z)
z_clean = z[clean] # ECKIGE Klammern
z_clean

[1] 1 2 3 5

## Matrizen in R

In [19]:
mat = matrix(c(1,2,3,4,5,6,7,8,9,10),nrow = 2, ncol = 5)
mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [20]:
t(mat) # transponieren

[,1] [,2]
[1,] 1     2  
[2,] 3     4  
[3,] 5     6  
[4,] 7     8  
[5,] 9    10

### Identitätsmatrix

In [21]:
d = diag(4)
d

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

In [22]:
zro = matrix(rep(0,6), ncol = 2, nrow = 3)
zro

[,1] [,2]
[1,] 0    0   
[2,] 0    0   
[3,] 0    0

In [28]:
vec = c(seq(2,20,2))
vec

[1]  2  4  6  8 10 12 14 16 18 20

In [30]:
evenmat = matrix(c(seq(2,20,2)), nrow = 2, ncol = 5)
evenmat

[,1] [,2] [,3] [,4] [,5]
[1,] 2    6    10   14   18  
[2,] 4    8    12   16   20

### Auswahl von Elementen bzw. Matrixteilen

In [31]:
evenmat[2,3]

[1] 12

In [32]:
evenmat[,-2]

[,1] [,2] [,3] [,4]
[1,] 2    10   14   18  
[2,] 4    12   16   20

In [33]:
evenmat[,2]

[1] 6 8

In [34]:
evenmat[2,3] = 32
evenmat

[,1] [,2] [,3] [,4] [,5]
[1,] 2    6    10   14   18  
[2,] 4    8    32   16   20

## Data Frames in R
Es handelt sich hier um eine spezielle Form von Matrizen.
Sie entsprechen aber eher Tabellen in relationalen Datenbanken, da hier die einzelnen Spalten **unterschiedliche Typen** haben dürfen!

In [42]:
data = data.frame(x= c(1:4), y= c("tom","jerry","luke","brian"))
data

x y    
1 1 tom  
2 2 jerry
3 3 luke 
4 4 brian

In [36]:
dfmat = data.frame(mat)
dfmat

X1 X2 X3 X4 X5
1 1  3  5  7   9
2 2  4  6  8  10

In [37]:
?data.frame # Erklärung zu data.frame

### Spalten hinzufügen

In [43]:
data$age = c(2,2,3,5)
data

x y     age
1 1 tom   2  
2 2 jerry 2  
3 3 luke  3  
4 4 brian 5

In [39]:
data$y

[1] tom   jerry luke  brian
Levels: brian jerry luke tom

In [44]:
data = data[c(2,3,1)] # umsortieren
data

y     age x
1 tom   2   1
2 jerry 2   2
3 luke  3   3
4 brian 5   4

In [45]:
names(data)

[1] "y"   "age" "x"

In [47]:
colnames(data) = c("Name", "Alter", "Nr")
data

Name  Alter Nr
1 tom   2     1 
2 jerry 2     2 
3 luke  3     3 
4 brian 5     4